export type SavedScript = { id: string; title: string; content: string; createdAt: string; updatedAt: string }
const dbName = 'next-studio-teleprompter'; const store = 'scripts'
function openDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { if (!('indexedDB' in window)) { reject(new Error('IndexedDB unavailable')); return }; const request = indexedDB.open(dbName, 2); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains(store)) request.result.createObjectStore(store, { keyPath: 'id' }) }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }) }
async function run<T>(mode: IDBTransactionMode, work: (objectStore: IDBObjectStore) => IDBRequest<T>) { const db = await openDb(); return new Promise<T>((resolve, reject) => { const transaction = db.transaction(store, mode); const request = work(transaction.objectStore(store)); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); transaction.oncomplete = () => db.close(); transaction.onerror = () => reject(transaction.error) }) }
export async function createScript(title: string, content: string) { const now = new Date().toISOString(); const script: SavedScript = { id: crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`, title: title.trim() || 'Untitled Script', content, createdAt: now, updatedAt: now }; await run('readwrite', (objectStore) => objectStore.put(script)); return script }
export async function updateScript(id: string, title: string, content: string) { const existing = await getScript(id); if (!existing) throw new Error('Script not found'); const script = { ...existing, title: title.trim() || 'Untitled Script', content, updatedAt: new Date().toISOString() }; await run('readwrite', (objectStore) => objectStore.put(script)); return script }
export async function getScripts() { const scripts = await run('readonly', (objectStore) => objectStore.getAll()) as SavedScript[]; return scripts.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
export function getScript(id: string) { return run('readonly', (objectStore) => objectStore.get(id)) as Promise<SavedScript | undefined> }
export async function deleteScript(id: string) { await run('readwrite', (objectStore) => objectStore.delete(id)) }
